name: Python CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      
      - name: Run linter and tests
        run: make check
      
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.TEST_COVERAGE}}
        with:
          coverageCommand: make test-coverage
          debug: true
